## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()`


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],[[3,5,6],
                                  [4,6,7],
                                  [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[3, 5, 6],
         [4, 6, 7],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important becuase the way many neural netowrks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(2,4)
random_tensor

tensor([[0.5222, 0.0654, 0.9544, 0.2479],
        [0.3610, 0.3384, 0.6869, 0.4256]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor_temp = torch.rand(size = (2,4,6,7))
random_tensor_temp

tensor([[[[0.1645, 0.2004, 0.1237, 0.4482, 0.8988, 0.9859, 0.6788],
          [0.9459, 0.0237, 0.2481, 0.0721, 0.4401, 0.1386, 0.9733],
          [0.1241, 0.8595, 0.2326, 0.8207, 0.2614, 0.7442, 0.6392],
          [0.9975, 0.1292, 0.0580, 0.2057, 0.2199, 0.9383, 0.8959],
          [0.7447, 0.5390, 0.7116, 0.4016, 0.3766, 0.5383, 0.6536],
          [0.3086, 0.7682, 0.7715, 0.8636, 0.5569, 0.1051, 0.0755]],

         [[0.7126, 0.7299, 0.1840, 0.2318, 0.1786, 0.7649, 0.9337],
          [0.9214, 0.1463, 0.5563, 0.0884, 0.3733, 0.7470, 0.5292],
          [0.7005, 0.9911, 0.8825, 0.9082, 0.5545, 0.8701, 0.8869],
          [0.0185, 0.7404, 0.3455, 0.6742, 0.0434, 0.0369, 0.4428],
          [0.4978, 0.3958, 0.3516, 0.9215, 0.1216, 0.6558, 0.4472],
          [0.4549, 0.0552, 0.6733, 0.0426, 0.4889, 0.7503, 0.7173]],

         [[0.1303, 0.3371, 0.3002, 0.1375, 0.3011, 0.4520, 0.4527],
          [0.0532, 0.1455, 0.9816, 0.3909, 0.3771, 0.3441, 0.9606],
          [0.4934, 0.1514, 0.0125, 0.1216, 0

### Zeros and ones

In [ ]:
# Create a tensor of all zeros (useful for masking a column)
zeros = torch.zeros(size = (2,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Creates a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # data type

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get depcrecated msg, use torch.arange() instead
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like (create the same tensor size)
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch & deep learning

1. Tensors not right datatype (might use float 16 with float 32 and get error)
2. Tensors not right shape (shapes must match)
3. Tensors not on the right device (might do operations on two tensors on diff devices)

In [ ]:
# Precision of number is a measure of the detail in how it's expressed in memory
# Float 32 tensor; 32 bits (single precision)
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 16 tensor; 16 bits (half precision); use if can use less space to compute faster

float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype is the tensor (e.g., float32 or float16)
                               device = None, # what device is your tensor on (e.g., cpu, gpu)
                               requires_grad = False) # if you want PyTorch to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor # sometimes it works -- just be aware of diff datatypes

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from Tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8363, 0.2137, 0.0454, 0.1175],
        [0.3148, 0.0681, 0.1867, 0.0586],
        [0.6771, 0.3164, 0.7980, 0.2300]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape} or {some_tensor.size()}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8363, 0.2137, 0.0454, 0.1175],
        [0.3148, 0.0681, 0.1867, 0.0586],
        [0.6771, 0.3164, 0.7980, 0.2300]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4]) or torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
random_tensor1 = torch.rand(3,4, dtype = torch.float16, device = 'cuda')
print(random_tensor)
print(f'Datatype of tensor: {random_tensor.dtype}')
print(f'Shape of tensor: {random_tensor.shape} or {random_tensor.size()}')
print(f'Device tensor is on: {random_tensor.device}')

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
# Element wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value = tensor[i] * tensor[i]
print(value)

tensor(9)
CPU times: user 1.8 ms, sys: 0 ns, total: 1.8 ms
Wall time: 1.71 ms


In [ ]:
%%time
torch.matmul(tensor,tensor) # use pytorch functions for complex bc more efficient

CPU times: user 174 µs, sys: 0 ns, total: 174 µs
Wall time: 104 µs


tensor(14)

In [ ]:
tensor @ tensor # another way to mat multiply -- matmul is more clear tho

tensor(14)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(2,3)) # produces error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2)) # Uses outer for dimension

## One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
torch.matmul(tensor_A,tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape # transposes

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

In [ ]:
torch.mm(tensor_A.T,tensor_B)

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# Find the mean
torch.mean(x) # error bc uses long/int but needs float

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# Find the mean with no error
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions purmuted (swapped) in a certain way

In [ ]:
x = torch.arange (1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape (1,7) # error because can't squeeze 9 into 7
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
x_reshaped = x.reshape (1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape (2,9) # can't do 18 elements
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [ ]:
x_reshaped = x.reshape (9, 1)
x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous tensor: {x_reshaped.shape}')

# Remove extra dimenions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous tensor: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor:{x_unsqueezed}')
print(f'\nNew shape:{x_unsqueezed.shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nNew tensor dim = 1:{x_unsqueezed}')
print(f'\nNew shape dim = 1:{x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape:torch.Size([1, 9])

New tensor dim = 1:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

New shape dim = 1:torch.Size([9, 1])


In [ ]:
# torch.permute - rearrange the dimensions of a target in a specified order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

x_original[0, 0, 0] = 100
print(f'Previous shape: {x_original.shape}')
print(f'Previous tensor: {x_original}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]
print(f'New tensor: {x_permuted}')

Previous shape: torch.Size([224, 224, 3])
Previous tensor: tensor([[[1.0000e+02, 1.0002e-02, 9.8424e-01],
         [2.8824e-01, 1.0991e-01, 9.7688e-01],
         [4.4340e-03, 8.2603e-01, 4.9447e-01],
         ...,
         [8.2938e-01, 8.2615e-01, 5.8477e-01],
         [3.6573e-01, 9.5326e-01, 3.7119e-02],
         [7.8377e-01, 4.2833e-01, 8.0613e-01]],

        [[3.8531e-01, 7.1479e-01, 8.3523e-01],
         [2.7440e-01, 6.6139e-01, 5.6268e-01],
         [2.8653e-01, 4.9152e-01, 6.9015e-01],
         ...,
         [9.7334e-01, 5.6220e-01, 7.2450e-01],
         [9.2460e-01, 5.6414e-01, 1.7210e-01],
         [7.4007e-01, 6.1905e-01, 5.9924e-01]],

        [[9.5858e-01, 8.0007e-01, 9.1482e-01],
         [8.6825e-02, 1.2561e-01, 4.0383e-01],
         [5.3951e-01, 4.6580e-01, 5.9039e-02],
         ...,
         [9.3861e-01, 7.8242e-01, 9.4497e-01],
         [2.3532e-01, 4.6360e-03, 7.8693e-01],
         [6.5992e-01, 8.3528e-01, 1.9401e-01]],

        ...,

        [[6.4503e-01, 4.7824e-01,

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
import torch
x = torch.arange(1, 10).reshape (1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim = 1)
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0,2,2]

(tensor(1), tensor(9))

In [ ]:
# You can also use ":" to select "all" of. atarget dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1], x[0, 1, 1]

(tensor([5]), tensor(5))

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

Numpy is. apopular scientific Python numerical computing library.

And because of this, PyTorch has functinoality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
tensor = torch.from_numpy(array).type(torch.float16)
tensor.dtype

torch.float16

In [ ]:
# change the value of array, what will this do to `tensor`
array = array + 1
array, tensor
# tensor does not change

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype # uses og datatype (PyTorch tensor)

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness

In [ ]:
torch.rand(3,3)

tensor([[0.5880, 0.8483, 0.0398],
        [0.5786, 0.4296, 0.2010],
        [0.0445, 0.1475, 0.5301]])

In [ ]:
import torch

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)
# if someone else were to run this cell, they would get different values

tensor([[0.6151, 0.8887, 0.4512, 0.8033],
        [0.8893, 0.8203, 0.4154, 0.0226],
        [0.6743, 0.8020, 0.8396, 0.9593]])
tensor([[0.6348, 0.0764, 0.3503, 0.1952],
        [0.9550, 0.3166, 0.8565, 0.5438],
        [0.6000, 0.0322, 0.1333, 0.3995]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42 # other common ones are 0, 1234, 77, 100

torch.manual_seed(RANDOM_SEED) # only works for one block of code
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_E = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)
print(random_tensor_E)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


Extra resources for Reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUS = faster computations on numbers, thanks to CUDE + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options..
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drives (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [ ]:
!nvidia-smi

Thu Sep 12 05:21:46 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

For PyTorch since it's capable of running compute on the GPU or CPU, it's best to practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g., run on GPU if available, else default to CPU

In [ ]:
# Count number of devices
torch.cuda.device_count() # might want to check devices to run different models on different gpus

1

### 3. Putting tensors (and models) on the GPU

The reason we want tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # also gives index of gpu (which gpu it's on)

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # gives error

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises